# Generated by Django 5.1 on 2025-12-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id_agente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('licencia_agente', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('preferencias_propiedad', models.TextField()),
                ('presupuesto_maximo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_registro', models.DateField()),
                ('dni', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('direccion_propietario', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('dni', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('tipo_propiedad', models.CharField(max_length=50)),
                ('num_habitaciones', models.IntegerField()),
                ('num_banos', models.IntegerField()),
                ('superficie_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_alquiler', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado_propiedad', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('descripcion', models.TextField()),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='app_inmobiliaria.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoVenta',
            fields=[
                ('id_contrato_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contrato', models.DateField()),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_cierre', models.DateField()),
                ('estado_contrato', models.CharField(max_length=50)),
                ('comision_agente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inmobiliaria.agente')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inmobiliaria.cliente')),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inmobiliaria.propiedad')),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inmobiliaria.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAlquiler',
            fields=[
                ('id_contrato_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_alquiler_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_contrato', models.CharField(max_length=50)),
                ('deposito_garantia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inmobiliaria.agente')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inmobiliaria.cliente')),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inmobiliaria.propiedad')),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inmobiliaria.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateField()),
                ('hora_visita', models.TimeField()),
                ('comentarios_cliente', models.TextField()),
                ('calificacion_propiedad', models.IntegerField()),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inmobiliaria.agente')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inmobiliaria.cliente')),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inmobiliaria.propiedad')),
            ],
        ),
    ]
